version: '3.8'

services:
  app:
    build:
      context: .  # Path to your application root where Dockerfile is located (builds from local image)
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=gifuser
      - MYSQL_PASSWORD=gifpassword
      - MYSQL_DATABASE=gif_db
    volumes:
      - ./.env:/usr/src/app/.env  # Mount the .env file inside the container
    depends_on:
      - mysql
    command: >
      bash -c "
      echo 'Waiting for MySQL to initialize...';
      sleep 18;
      echo 'Running database setup...';
      node setupDatabase.js;
      echo 'Starting the application...';
      mkdir -p ~/.aws && \
      echo '[default]' > ~/.aws/credentials && \
      echo 'aws_access_key_id=ASIA5DYSEEJ44ZMQDZFC' >> ~/.aws/credentials && \
      echo 'aws_secret_access_key=pQ07tLagmHB63S+ZgeSjVd5zpRfXV7PvHdlAdSQF' >> ~/.aws/credentials && \
      echo 'aws_session_token=IQoJb3JpZ2luX2VjEFgaDmFwLXNvdXRoZWFzdC0yIkYwRAIgBTnpDx1uM/IwKv6UCN97drC1GcPtGtW3jyGKWCRYtGoCIB85jKKTjg8DXPmmJWJ6ofdI7iwGqnwp+tE9T8Y/2hSpKq4DCLH//////////wEQAxoMOTAxNDQ0MjgwOTUzIgyNweFdruA4CZZOhPIqggNWrJELFID0y6Y6ja77anI0z4FbOUwFTY5Rvbk1DL5dzdXbnxf+O+rHvWvkGf8jmaDNZB56gStGrszevypjTTG4dYwQb/oYYf2+7WjeSzyNijBj7ikUUeRk0SBNEX51JkLjZcaVrZM1FdkY0ftV8IkeebYeqObnWBf2tMKHJUuzXBJAqC4BeAOvpLM0JUGzMQqg2aOm3xN/a1+WNOTmD8fNR7CzvKyvxQitqjQirRxp1Lgiji/gXDrK1zwLt0/zT6ZBhU1YNiACEEul4HMbe91OBYCRH6uKGVetgTAjjP0ww5evpZ0vAZlHBEOIQZ5qCAj/2m13CtTLKyPizKqTnofr/7j7bgo//iebDZc0xFA22G/ceGj6W9fvOF3Lx+A9rESzDLel+SwLxI07NIy0b4OlO/VztiUaPlKlrdG3dzIjCbrV+/X26Q1OC9qS0zD5qLgPlPt//0kUx+iJ8K8skyoeq2NgK51eq2DS+15IlkAQn4EM9ZwAzeZOVH+4al1Yth/nCzD3iqy4BjqnAZ0X/UFTwhYVWuGWXxWpOZg1rsBhvqZrIR+Yn2PTKdL/EAEA6keoR1hyj4HNJd53uBPS1TNkst6qAT8cZVGSzpZj/FTfLD17cLnejPLQK0+BDtZeu35PKLa/0mRLNsMhDttb+rOsS7+6lfx42EybT7WNN+t5Gzm7dAw7hqxV41wwG1e2vFNkSF6T0Al6S9AeKzj/i4KAHDHJnKCweXR2Ja3oaKanVrK3' >> ~/.aws/credentials && \
      echo '[default]' > ~/.aws/config && \
      echo 'region=ap-southeast-2' >> ~/.aws/config && \
      node GifApplicationIndex.js"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=gif_db
      - MYSQL_USER=gifuser
      - MYSQL_PASSWORD=gifpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: